### ISSUE TITLE
Wrong RSS feed is converted

### ISSUE THREAD

**Issue by bvtsang** [dariusk/rss-to-activitypub#10]
1. Visit https://bots.tinysubversions.com/convert/
2. Enter https://backend.deviantart.com/rss.xml?type=deviation&q=by%3Asakimichan+sort%3Atime+meta%3Aall as the feed URL
3. Enter sakimichan_deviantart as the username
4. Click Submit

Expected: https://backend.deviantart.com/rss.xml?type=deviation&q=by%3Asakimichan+sort%3Atime+meta%3Aall converted into an ActivityPub account
Observed: https://backend.deviantart.com/rss.xml converted into an ActivityPub account

https://bots.tinysubversions.com/u/sakimichan_deviantart

**Comment by dariusk** [comment]
Thanks! I think I see what's wrong and I'll try to fix it soon.

**Comment by dariusk** [comment]
Hi, I fixed it. Silly error on my part. You can follow the new account for sakimichan at:

https://bots.tinysubversions.com/u/sakimichan_da/

And future DA accounts should work just fine.
