### ISSUE TITLE
Improve error message for incorrect URLs

### ISSUE THREAD

**Issue by deutrino** [dariusk/rss-to-activitypub#12]
When pasting in an incorrect URL to a feed (for example, with "view-source:" still prepended), the error message is "Bad Request." This isn't helpful, especially if the typo/etc is at the front of the URL, which may be invisible because of the width of the text box. A more helpful message for "I couldn't find a feed at that URL" would be useful. See #8.

**Comment by dariusk** [comment]
Hi! Great suggestion. I fixed this, you now get a message like this:

<img width="873" alt="image" src="https://user-images.githubusercontent.com/266454/53269614-34cb9280-369e-11e9-8ac4-295f24ccfc66.png">
