### ISSUE TITLE
Feed pages missing attribution link for server software

### ISSUE THREAD

**Issue by Skirmisher** [dariusk/rss-to-activitypub#14]
As it stands, the pages for individual feeds are self-explanatory, but lack context in the form of a link to the project's GitHub page, or even a link to the landing page of the site itself. I feel those would be appropriate in order to e.g. guide those who discover an account via a boost.

**Comment by dariusk** [comment]
Good idea. Here's what the new page looks like (I also added a link to the source code on the front page):

<img width="936" alt="image" src="https://user-images.githubusercontent.com/266454/53295178-bf011d00-37aa-11e9-934b-a993b41fec74.png">
