### ISSUE TITLE
Error on feed from rss-bridge

### ISSUE THREAD

**Issue by ghost** [dariusk/rss-to-activitypub#15]
There's an error when you try to create an account from a twitter rss bridge.
For example this feed doesn't work :
https://rss-bridge.cheredeprince.net/?action=display&bridge=Twitter&u=RaccoonDaily&format=Atom

I'm getting "Error: Unexpected close tag Line: 15 Column: 7 Char: >"

Is it because atom isn't supported ?

**Comment by dariusk** [comment]
It appears to be failing on emoji. I'll look into it!

**Comment by ghost** [comment]
Thanks ! :)

**Comment by dariusk** [comment]
@Dostoi I fixed it! Silly error on my part. You can now see the page for the feed here: https://bots.tinysubversions.com/u/raccoon_daily/ and subscribe at `@raccoon_daily@bots.tinysubversions.com`

**Comment by ghost** [comment]
Thanks a lot :)
