### ISSUE TITLE
Issue with feed update

### ISSUE THREAD

**Issue by ghost** [dariusk/rss-to-activitypub#19]
I created an account for a twitter feed after you've fixed the issue but it doesn't seem to create new items when something new appears on the feed. Is there some delay before creating items ?
For example this account has 4 new items on its feed but they doesn't appear to have been created on the profile page :
https://bots.tinysubversions.com/u/larueourien1

**Comment by dariusk** [comment]
Hi, what software are you using to view the feed (Mastodon, Pleroma, etc)?

**Comment by husimo** [comment]
Hello, 
I have the same problem.
The first loading of rss feed is working but then a new content is pushed, it's not working.
Example with my Mastodon's user feed :
https://social.nealta.fr/users/husimo.rss (3 items)
https://bots.tinysubversions.com/u/husimo (2 items)
Thank you

**Comment by husimo** [comment]
Seems to be working know, thank you

**Comment by ghost** [comment]
On mastodon. After some time it seems to be working but not to be updated often. Items are pushed together from time to time and not on appearance in the rss feed.

**Comment by dariusk** [comment]
I believe I've solved this issue by changing the architecture to use `beanstalkd` for message queueing.
