### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by Zerolemis** [dariusk/rss-to-activitypub#22]
Since 3 days ago the RSS feeds stopped to update, may I ask what happened?

**Comment by dariusk** [comment]
I am still seeing updates. Can you tell me which feed you are not seeing updates on, and can you tell me if you are on Pleroma or on Mastodon or something else?

**Comment by Zerolemis** [comment]
All the feeds I suscribed stopped to update. For example:
https://bots.tinysubversions.com/u/DWabstract

It's on Mastodon.

**Comment by dariusk** [comment]
Okay, I've fixed this. Thank you for the bug report!

**Comment by Zerolemis** [comment]
Now repeating toot is happening again...
e.g. 
https://bots.tinysubversions.com/m/98ea2ad1e48238bd4a5274225d1d7f07
https://bots.tinysubversions.com/m/54c6683543eac6b21078ebb4f3ee7474
https://bots.tinysubversions.com/m/01f7d62ae7588bb2410bc3fbc2457aee

**Comment by dariusk** [comment]
I would wait and see if the repeats happen again -- it's possible this is a one-time thing because I had to process a large queue.

**Comment by dariusk** [comment]
Okay it's definitely still happening and I will try and fix it today.

**Comment by tachyons** [comment]
Same here

**Comment by dariusk** [comment]
@tachyons Thanks. I believe I have fixed it as of ten minutes ago. Hopefully I'm right and this will stop the repeated posts.

**Comment by tachyons** [comment]
It will be great if you send delete request to duplicated toots?
