### ISSUE TITLE
Error updating feeds

### ISSUE THREAD

**Issue by husimo** [dariusk/rss-to-activitypub#23]
Hello,
I have the following error running "node updateFeeds.js" : 
```
/app/updateFeeds.js:21
  console.log(count, feed.feed);
                          ^

TypeError: Cannot read property 'feed' of undefined
    at Timeout.doFeed [as _onTimeout] (/app/updateFeeds.js:21:27)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
```

When I comment `console.log(count, feed.feed);` located line 21, it's working properly. So I guess you just forgot to comment it before pushing.

Have a nice day :-)

**Comment by dariusk** [comment]
Closing this because the code no longer works this way. We now consume items from a message queue instead of using a for loop.
