### ISSUE TITLE
Small improvement to disable item title in content sent

### ISSUE THREAD

**Issue by husimo** [dariusk/rss-to-activitypub#24]
Hello,
I just made a little tweak, disabling the item title to being sent. Indeed, I'm using "rss-bridge" to be able to follow twittos using RSS feeds. Nonetheless, the bridge uses part of the tweet content as title.

Consequently, then using rss-to-activity-pub you have something like this : 
![image](https://user-images.githubusercontent.com/30700841/56096701-f313d700-5eeb-11e9-895d-cfeb4fd397d3.png)

You have twice the same tweet.

So I changed a little bit the file `updateFeeds.js`, replacing : 
```js
 let message = `<p><a href="${item.link}">${item.title}</a></p><p>${item.content || ''}</p>`;
```

by
```js
          let message;
          if(item.link.match('/twitter.com/')) {
             message = `${item.content}`;
          }
          else {
             message = `<p><a href="${item.link}">${item.title}</a></p><p>${item.content || ''}</p>`;
          }
```

So if the item links to twitter.com, only the content of item is sent to Mastodon. See how it is rendering : 

![image](https://user-images.githubusercontent.com/30700841/56096734-530a7d80-5eec-11e9-91cd-61a7ca53b323.png)

Don't know if it can be useful in the code but I thought maybe somebody could be interested to doing the same thing.

I know it's not a good place to share a tweak and I'm sorry, I didn't know anywhere else to put it.

Have a nice day

**Comment by bugsysop** [comment]
Thanks! Very usefull for me as I'm also using RRS-Bridge

**Comment by dariusk** [comment]
Fixed, thanks!
