### ISSUE TITLE
Don't send a new toot when rss feed item is updated

### ISSUE THREAD

**Issue by husimo** [dariusk/rss-to-activitypub#25]
Hello,
It seems that some websites have the bad habit to update their existing articles in order to "bump" their articles in their rss feed.
Would it be possible to not send new toot when an article is "updated" ?
Thank you :-)

**Comment by dariusk** [comment]
It's difficult to test this without an example. Can you give me an example of an RSS feed that does this? I can monitor this and check on what it's doing.
