### ISSUE TITLE
Feed items are sent again on each update 

### ISSUE THREAD

**Issue by husimo** [dariusk/rss-to-activitypub#26]
Hello,
I have a feed, https://multinationales.org/spip.php?page=backend ; it's items are sent each time I update my feed.
This is the profile : https://rss-bots.nealta.fr/u/multinationales
I can't figure out why...It happens only with that feed. Could it be related to a malformed rss feed ?
Thank you

**Comment by dariusk** [comment]
Hi, I looked at this when you posted it and couldn't find a particular reason but it seems like there might have been some kind of malformed RSS going on.
