### ISSUE TITLE
Suspending/deleting an account

### ISSUE THREAD

**Issue by inputsh** [dariusk/rss-to-activitypub#27]
Hi, I have created an account from a feed that turned out to be far too noisy. Since nobody else is following it, is there a way to stop it from sending more updates and/or delete it all together?

**EDIT:** In case it's not obvious: I'm running rss-to-activity on my own server, not using the demo version.

**Comment by dariusk** [comment]
Hi! Sorry for the delay in response.

If this is on your own server, you could always log in to sqlite and delete the `feeds` row for the entry and the `accounts` row for the entry.

$ sqlite3 bot-node.db
> delete from feeds where username = "theusername" ;
> delete from accounts where name = "theusername@YOURDOMAIN";

This will prevent the update script from sending it out.

I should probably create a little admin interface to do this...
