### ISSUE TITLE
Remove redundant line breaks

### ISSUE THREAD

**Issue by ghost** [dariusk/rss-to-activitypub#28]
### Motivations

Some of my feeds are converted by RSSHub from weibo.com. For a better experience in RSS reader, RSSHub appends 2  `<br>` tags to each images, which will be converted to trailing line breaks in Mastodon federation ...

Here is an example: https://bots.tinysubversions.com/m/f2e894bf8e3fc844fb3808bbc639fe0e .

### How to implement it, for example

1. Replace images elements with links.
2. Remove all trailing space and `<br>` tags at the end.
3. If more than 1 `<br>` tag appear, remove all the redundant `<br>` tags.

**Comment by dariusk** [comment]
Good idea. Here's the encoded HTML from the post in question (mostly for my own reference)

```html
<p><a href=\"https://weibo.com/2794283127/HtQ4ExfVM\">去两人主页看了看，都删了，现在跟没事儿人似的（那个@Jjin628 连ID都改了网页链接 这里有死者后背的照片。...</a></p>&#x53BB;&#x4E24;&#x4EBA;&#x4E3B;&#x9875;&#x770B;&#x4E86;&#x770B;&#xFF0C;&#x90FD;&#x5220;&#x4E86;&#xFF0C;&#x73B0;&#x5728;&#x8DDF;&#x6CA1;&#x4E8B;&#x513F;&#x4EBA;&#x4F3C;&#x7684;&#xFF08;&#x90A3;&#x4E2A;<a href=\"/n/Jjin628\">@Jjin628</a> &#x8FDE;ID&#x90FD;&#x6539;&#x4E86;<a data-url=\"http://t.cn/EK7SKwo\" href=\"https://m.weibo.cn/u/1752110562?uid=1752110562&amp;luicode=10000011&amp;lfid=1076032794283127\" data-hide=\"\">&#x7F51;&#x9875;&#x94FE;&#x63A5;</a> &#x8FD9;&#x91CC;&#x6709;&#x6B7B;&#x8005;&#x540E;&#x80CC;&#x7684;&#x7167;&#x7247;&#x3002;&#x548C;&#x56FE;5&#x8BF4;&#x7684;&#x7EC6;&#x8282;&#x201C;&#x80CC;&#x540E;&#x6345;&#x4E86;&#x51E0;&#x5200;&#x201D;&#x5BF9;&#x6BD4;&#x4E86;&#x4E00;&#x4E0B;&#x8F6C;&#x53D1; <a href=\"https://weibo.com/2084561435\" target=\"_blank\">@&#x8568;&#x4EE3;&#x971C;&#x86DF;</a>: &#x4EBA;&#x95F4;&#x5730;&#x72F1;&#x3002; <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
```

**Comment by dariusk** [comment]
I believe I've updated this to work. Please re-open this issue if it's not fixed. Thanks!

**Comment by ghost** [comment]
Thanks, it works now! 🍻

**Comment by ghost** [comment]
Sorry for bothering you, but it fails today. A rollback happens? 😂

**Comment by dariusk** [comment]
Can you point me to the exact post?

**Comment by ghost** [comment]
From the same feed: https://bots.tinysubversions.com/m/ab86910692bb370e1d5845e75107efec
Now it works again 😂

**Comment by ghost** [comment]
BTW, is it possible to remove empty `<p>` tags?

Some of my feeds use `<p>` to wrap images, which will become empty line breaks in Mastodon federation.

Example: https://bots.tinysubversions.com/m/e913bea7b538662ccfd1b60a9f3d4835
