### ISSUE TITLE
[query] Are Atom feeds supported?

### ISSUE THREAD

**Issue by lofidevops** [dariusk/rss-to-activitypub#33]
From the name I assumed only RSS feeds are supported, but I see references in a few comments to Atom, e.g. https://github.com/dariusk/rss-to-activitypub/issues/15

Are Atom feeds supported?

**Comment by lofidevops** [comment]
https://bots.tinysubversions.com/u/matrixblog proves that they are supported :)

**Comment by dariusk** [comment]
Indeed they are! I should update the language to note this (I just installed an RSS parser package and didn't bother to notice that it provided Atom as well.)
