### ISSUE TITLE
[query] Suggestions for sharing a domain with Mastodon

### ISSUE THREAD

**Issue by lofidevops** [dariusk/rss-to-activitypub#34]
It looks like the reference instance https://bots.tinysubversions.com lives completely independently of any other ActivityPub service, e.g. Mastodon. Is it possible to set up the `rss-to-activitypub` service so it can share a domain with another service. In other words, a person can post from `@human@example.com` and a feed bot from `@bot@example.com`

Or would they have to live at separate domains? `@human@example.com` and `@bot@feeds.example.com`

**Comment by dariusk** [comment]
I think it's good practice to keep separate servers/services on separate domains (by subdomain). Specifically the way ActivityPub works, if we had the RSS thing on the same domain as Mastodon, every time someone tried to create an RSS account like @foo@example.com, we would have to first check if a Mastodon user existed at @foo@example.com. This is _possible_ to do but to me it also opens up a can of worms around security and identity issues. So my opinion is that this should live on a different domain (or subdomain) than other AP services.
