### ISSUE TITLE
Show error message if the feed has been converted 

### ISSUE THREAD

**Issue by ghost** [dariusk/rss-to-activitypub#35]
Today I try to convert a feed but nothing happened, so I open the console and it turns out that this feed has been converted to another username. 😂

**Comment by dariusk** [comment]
Can you tell me what feed? When I try this I get an error message and then it redirects me to the correct user.

<img width="727" alt="image" src="https://user-images.githubusercontent.com/266454/58372708-5115e000-7ed6-11e9-921e-7d9ee8cb441e.png">

**Comment by ghost** [comment]
OK, now it works... 🍺
