### ISSUE TITLE
No toot since end of April

### ISSUE THREAD

**Issue by Zerolemis** [dariusk/rss-to-activitypub#37]
Hello, since the end of April some of my feed seems stop to send new toots when the source updates. For example:
https://bots.tinysubversions.com/u/AfricanAsianLiteratureBot 
https://bots.tinysubversions.com/u/Broadwaycnbot 
etc.
Can you figure out what's wrong?

**Comment by dariusk** [comment]
That website, https://api.izgq.net, that you are using to create/convert feeds, has blocked access from my server to their API. I'm sure I'm hitting some sort of rate limit. I'm hitting their endpoint once every fifteen minutes per bot. You have a lot of bots listed so it must be blowing through them.

**Comment by Zerolemis** [comment]
I see... I suppose it's because there's too much followers to those account. Thank you for the reply!

**Comment by Zerolemis** [comment]
Is it possible to slow down the rate of hitting?

**Comment by dariusk** [comment]
Sorry, I don't think I can really support this.
