### ISSUE TITLE
Hard-coded domain name in HTML

### ISSUE THREAD

**Issue by ghost** [dariusk/rss-to-activitypub#4]
The URL https://bots.tinysubversions.com/u/… is hard coded in public/convert/index.html. Line 77 in the version I have, message guarded by `if (myJson.title)`. Also, https even though I haven't given it a certificate so HTTPS is turned off.

Not an problem for me personally; I'm just playing with it to help get my head round ActivityPub. Thanks for the help with that.

**Comment by dariusk** [comment]
Fixed in b26955dc3c13a2de1a219015c91ae08d82e2b11b, thanks!
