### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:11300

### ISSUE THREAD

**Issue by husim0** [dariusk/rss-to-activitypub#40]
Hello,
I have the following error executing updateFeeds.js : `(node:2279) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:11300`.
Thank you :)

**Comment by husim0** [comment]
Ok it's because I don't have beanstalkd. Thank you :-)

**Comment by dariusk** [comment]
Ah, yeah, I added that a couple months ago!
