### ISSUE TITLE
Misskey support

### ISSUE THREAD

**Issue by ghost** [dariusk/rss-to-activitypub#42]
[Misskey](https://misskey.io) is another federated blogging platform that can interact with Mastodon. I want to follow some RSS accounts on Misskey but it stuck in `Processing` ...

PS: Misskey doesn't have a documentation about federation, you may need to read the [source code](https://github.com/syuilo/misskey/tree/develop/src/remote) to fix it. And here is a reference on how they handle Pleroma federation: https://git.pleroma.social/pleroma/pleroma/issues/259

**Comment by dariusk** [comment]
Unfortunately I can't personally take the time to support projects that don't have documentation about federation. You may wish to contact Misskey and ask them to document their federation compatibility.
