### ISSUE TITLE
[Feature Request] Audio files as media attachments

### ISSUE THREAD

**Issue by ghost** [dariusk/rss-to-activitypub#44]
Mastodon v2.9.2 supports audio upload and federation (mp3/mpga). It would be great if rss-to-activitypub adds audio files to media attachments.

**Comment by dariusk** [comment]
Great idea. I will add this.

**Comment by dariusk** [comment]
Okay, now any RSS feed that supports the standard iTunes podcast enclosure format will have the mp3 as an attachment on Mastodon 2.9.2+.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/266454/60374713-96886a00-99ba-11e9-86a1-089c4125b090.png">

**Comment by ghost** [comment]
Bravo!
