### ISSUE TITLE
Hasn't update since 4 days ago

### ISSUE THREAD

**Issue by Zerolemis** [dariusk/rss-to-activitypub#54]
Hello, the rss feed seems stop updating since 4 days ago, any solution to that please? I really rely on this awesome tool!

Thank you!

**Comment by Zerolemis** [comment]
A few seconds after I oppened this issue it start updating again... Anyway, hope it won't stop in the future. Thank you so much!

**Comment by dariusk** [comment]
No problem, someone else asked just before you did and i kicked it back
online!

**Comment by Zerolemis** [comment]
Thank you so much!
