### ISSUE TITLE
bots.tinysubversions.com is hard coded 

### ISSUE THREAD

**Issue by decentral1se** [dariusk/rss-to-activitypub#6]
When I run a server locally, I see my generated feed URL have this domain name hard coded.

**Comment by dariusk** [comment]
Thank you, I will fix this when I get a chance.

**Comment by phormanns** [comment]
look at my pull request 
https://github.com/dariusk/rss-to-activitypub/pull/7

**Comment by dariusk** [comment]
Fixed in b26955dc3c13a2de1a219015c91ae08d82e2b11b thanks to @phormanns
